### PR TITLE
use default target of _blank, override where appropriate

### LINKED ISSUE #22: All links should open in new tab
currently the links take you away from the tutorial page ... which is annoying.

### PR DESCRIPTION
**Pull request by nerdEd**
Fixes #22. We'll have to be careful when adding new nav links to include a target of "_self" but I think this solution is preferable to manually adding target="_blank" to all other links (which there are more of).

### CODE REVIEW

**Comment by latazzajones** [comment]
I'm not opposed to this. I'm wondering if it's worth moving it into the config and using a liquid tag for it in the view. Maybe that's kinda over-engineering a super simple thing - but then it's near similar stuffs like baseurl. 

Then maybe put a note in the README about needing to specify self to prevent opening in a new tab.

**Review by latazzajones — COMMENTED** [review]
I'm not opposed to this. I'm wondering if it's worth moving it into or referencing it in the config and using a liquid tag for it in the view. Maybe that's kinda over-engineering a super simple thing - but then it's near similar stuffs like baseurl.

Then maybe put a note in the README about needing to specify self to prevent opening in a new tab.

**Comment by nerdEd** [comment]
@latazzajones super reasonable suggestions. Done.

**Comment by latazzajones** [comment]
Sweet! Thanks for picking this up - awesome approach to the problem.

**Pull request merged**
