### PR TITLE
win10, win8, and win7 installation instructions

### PR DESCRIPTION
**Pull request by beverlyguillermo**
I didn't add the links that Doug had in his branch to prevent conflicts.  These are just the files for the win10 markdown files.

### CODE REVIEW

**Comment by latazzajones** [comment]
@beverlyguillermo this is looking great! do you mind pulling master and checking it out once more quickly. I have the ux for the jekyll site in place now - so you'll be able to see how it all fits together. I think Doug had to do some tweeks to the classes he was using. 

his pr is here if you want to check it out: https://github.com/bmoreonrails/rails_tutorial/pull/4

I'll merge it when you're happy with it - then we can make smaller stories to get some of the UX of the related pages looking sharper.

**Comment by latazzajones** [comment]
@beverlyguillermo is this ready to merge - or do you want me to wait a bit?

**Comment by beverlyguillermo** [comment]
@latazzajones Now you have me second guessing! I added some more steps for checking the windows version, but all the steps to install everything is correct so I think it is ready to merge.

**Comment by latazzajones** [comment]
🎉 yay! @beverlyguillermo this is great. Thank you for doing all of this - I know that windows is a lot to manage. I've merged it - but don't hesitate to make adjustments if something comes up!

**Pull request merged**
