### PR TITLE
MacOS Installation Revision

### PR DESCRIPTION
**Pull request by oliikit**
@solipet - FYI. 

I think ending on creating a new Rails project may be a good thing. It just needs to be added into the Windows version. I included instructions on how to delete the folder and made it clear that that's not what the students are going to use for the actual tutorial.

### CODE REVIEW

**Comment by latazzajones** [comment]
@solipet did you have a chance to look at this? Let me know if I should merge it ... Also @foxiae same as before - take a sec and fix the conflict when you have a chance and we'll get it on master. Thanks!

**Comment by solipet** [comment]
@latazzajones yes, I did :-) @foxiae did you see my comment?

**Comment by oliikit** [comment]
Yeah, I'll be able to look at it tomorrow. I'll be in and out until next
Tuesday.

**Comment by latazzajones** [comment]
@foxiae any time to check this out? I'd like to get it merged since we have testers trying out the tutorial.

**Comment by oliikit** [comment]
@latazzajones sorry about that! Fixes made :)

**Pull request merged**
