### PR TITLE
Linux Installation Instructions.

### PR DESCRIPTION
**Pull request by oliikit**

### CODE REVIEW

**Comment by latazzajones** [comment]
@foxiae I can merge this if you want but maybe you could fix the conflict ... looks like it should be quick and easy to resolve.

**Comment by latazzajones** [comment]
@foxiae same here!

**Comment by oliikit** [comment]
@latazzajones done!

**Comment by latazzajones** [comment]
@foxiae looks like there's still a conflict here ...

**Comment by oliikit** [comment]
@latazzajones all resolved now!

**Pull request merged**
